#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

# Use the provided interface, otherwise the device used for the default route.
if [[ -n $BLOCK_INSTANCE ]]; then
  IF=$BLOCK_INSTANCE
else
  IF=$(ip route | awk '/^default/ { print $5 ; exit }')
fi

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${IF} ]] && exit

#------------------------------------------------------------------------

if [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]]; then
  echo down # full text
  echo down # short text
  echo \#FF0000 # color
  exit
fi

# if no interface is found, use the first device with a global scope
IPADDR4=$(ip addr show $IF | perl -n -e "/inet ([^\/]+).* scope global/ && print \$1 and exit")
IPADDR6=$(ip addr show $IF | perl -n -e "/inet6 ([^\/]+).* scope global/ && print \$1 and exit")

case $BLOCK_BUTTON in
  1) notify-send "$IF:\n$IPADDR4\n$IPADDR6" ;;
  3) echo -n "$IPADDR4\n$IPADDR6" | xclip -q -se c ;;
esac

#------------------------------------------------------------------------

IF_SHORT=$(echo $IF | cut -c1-1)

IPSUM=""
if [ "$IPADDR4" ]; then
	IPSUM="${IPSUM}4"
fi
if [ "$IPADDR6" ]; then
	IPSUM="${IPSUM}6"
fi
if [ "$IPSUM" == "46" ]; then
	IPSUM="8" 
fi

echo "🌎 ${IF_SHORT}${IPSUM}"
