#!/bin/bash

case $BLOCK_BUTTON in
  # LeftClick - Spotify
  1) echo "spotify" > ~/.i3/player ;;
  # RightClick - VLC
  3) echo "vlc" > ~/.i3/player  ;;
esac

cat ~/.i3/player | cut -c1-1 | awk '{print toupper($0)}'
