#!/bin/bash

base_dir=$(dirname $0)

# files
city_file="$base_dir/weather_cities"
index_file="$base_dir/weather_cities_index"
api_file="$base_dir/weather_api"
# init
if [ ! -f $city_file ]; then
	echo "CZ-Prague" > $city_file
fi
if [ ! -f $index_file ]; then
	echo "1" > $index_file
fi
# variables
index=$(cat $index_file)
city=$(sed "${index}q;d" $city_file)
api=$(cat $api_file)

$base_dir/wunderground-temperature.py $api "$city"
