#!/bin/bash

source ~/.i3/players # Load lists of players
name="$(cat ~/.i3/player)" # Load current player

if [ "$name" = "auto" ]; then
for i_name in ${players[@]}; do
		if [ "$i_name" = "auto" ]; then continue ; fi
		pgrep $i_name 1>/dev/null 2>/dev/null
		if [ $? -eq 0 ]; then
			name="$i_name"
			break
		fi
	done
fi

if [ "$name" = "auto" ] || [ ! "$name" ]; then
	notify-send "ERROR: Cannot find player for $@!"
	exit 0
fi

#shift
PATHS="org.mpris.MediaPlayer2.$name /org/mpris/MediaPlayer2"
DBUS_SEND="dbus-send --type=method_call --dest=$PATHS"
RC="$DBUS_SEND org.mpris.MediaPlayer2.Player"
if [ "$@" = "prev" ]; then
    $RC.Previous
elif [ "$@" = "stop" ]; then
    $RC.Pause
elif [ "$@" = "toggle" ]; then
    $RC.PlayPause
elif [ "$@" = "next" ]; then
    $RC.Next
elif [ "$@" = "random" ]; then
    current=$(mdbus2 $PATHS org.freedesktop.DBus.Properties.Get org.mpris.MediaPlayer2.Player Shuffle)
    if [ "$current" = "( true)" ]; then
        other=false
    else
        other=true
    fi
    $DBUS_SEND org.freedesktop.DBus.Properties.Set string:org.mpris.MediaPlayer2.Player string:Shuffle variant:boolean:$other
else
    notify-send "Command not found for player $name: $@"
    exit 1
fi
